name: Go Checks
on:
  push:
    branches: [ main, develop, develop-react ]
  pull_request:
    branches: [ main, develop, develop-react ]

jobs:
  check:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: '1.24'

      - name: Install tools
        run: go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest

      - name: Sync vendor directory
        run: |
          cd backend
          go mod download
          go mod vendor

      - name: Build
        run: |
          cd backend
          go build ./cmd/server

      - name: Test
        run: |
          cd backend
          go test -race -coverprofile=coverage.txt ./...

      - name: Lint
        run: |
          cd backend
          golangci-lint run

      - name: Security scan
        run: |
          cd backend
          go run github.com/securego/gosec/v2/cmd/gosec@latest .
